<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" name="ydma" top="ydma">
    <files>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/data_transfer.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/rasterization2_m.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/data_redir_m.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/coloringFB_top_m.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/coloringFB_bot_m.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/zculling_top.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/operators/zculling_bot.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host/typedefs.h" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
        <file name="/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host/top.cpp" sc="0" tb="false" cflags="-g -I/tools/Xilinx/Vivado/2021.1/include -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512 -I/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/rendering512/host" csimflags="" blackbox="false"/>
    </files>
    <solutions>
        <solution name="solution" status=""/>
    </solutions>
</AutoPilot:project>

