catch {::common::set_param -quiet hls.xocc.mode csynth};
catch {::common::set_param -quiet hls.enable_scout_hidden_option_error false};
# 
# HLS run script generated by v++ compiler
# 

open_project ydma
set_top ydma
# v++ -g, -D, -I, --advanced.prop kernel.ydma.kernel_flags
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host/top.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host/typedefs.h" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_weight_y_1.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/data_transfer.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_weight_x3.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_xyz_calc.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/outer_product1.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_weight_y_2.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/tensor_weight_y1.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/tensor_weight_x1.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/outer_product2.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/tensor_weight_y2.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/tensor_weight_x2.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_weight_y_3.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_weight_x1.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/flow_calc_1.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/output_fun.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/flow_calc_2.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
add_files "/home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/operators/gradient_weight_x2.cpp" -cflags " -g -I /tools/Xilinx/Vivado/2021.1/include -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512 -I /home/dopark/workspace/zcu102_tuning/prflow_riscv/input_src/optical_flow512/host "
open_solution -flow_target vitis solution
set_part xczu9eg-ffvb1156-2-e
create_clock -period 150.000000MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname ydma
catch {::common::set_param -quiet hls.enable_synthesis_check_sw_only true};
csynth_design -synthesis_check
close_project
puts "HLS completed successfully"
exit
